name: Check Pull Request

on:
  push:
    branches:
      - main  # 或者您的默认分支

jobs:
  check_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run setup.sh
      run: |
        chmod +x setup.sh
        ./setup.sh

    - name: Run run_bash.sh and check for errors
      run: |
        chmod +x run_bash.sh
        output=$(./run_bash.sh)
        echo "$output"

        # 检查输出是否包含 "error" 字符串
        if echo "$output" | grep -q "error"; then
          echo "Error found in the output. Pull request failed."
          exit 1
        else
          echo "No errors found in the output. Pull request succeeded."
        fi
